theme: jekyll-theme-architect

title: [wadl]
description: [Web Application Description Language - Specification and Tools]

# sidebar links url
links:
  source: https://github.com/javaee/wadl
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

